title: "Jongyoon Park"
description: "COMP110 Continuous Improvement Project — pre-lecture videos analysis."
author: "Jongyoon Park"
email: "vencei020502@gmail.com"

baseurl: "/comp110-continuous-improvement"
url: "https://park-jongyoon.github.io"

theme: null
plugins: []

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor